resources:
- name: tanzu-rel-repo
  type: git
  source:
    uri: git@github.com:nnikunj-vmw/tanzu-release.git
    private_key:  ((git-private-key))
    branch: main
  check_every: 1m
jobs:
- name: release-notification-pipeline
  plan: 
  - get: tanzu-rel-repo
    trigger: true
  - task: parse-bom
    vars:
      docker_user_name: ((docker_user_name))
      docker_password: ((docker_password))
    outputs:
      - name: bom-version
    file: tanzu-rel-repo/tasks/parseBom.yaml


  - task: update-runner-pipeline
    vars:
      concourse_coordinates: "http://192.168.1.6:8080"
      docker_user_name: ((docker_user_name))
      docker_password: ((docker_password))
    inputs:
      - name: bom-version
      - name: tanzu-rel-repo
    file: tanzu-rel-repo/tasks/registerTask.yaml
    

      