resources:
- name: tanzu-rel-repo
  type: git
  source:
    uri: git@github.com:nnikunj-vmw/tanzu-release.git
    private_key:  ((git-private-key))
    branch: main
  check_every: 1m
jobs:
- name: release-notification-pipeline
  plan: 
  - get: tanzu-rel-repo
    trigger: true
    
  - task: list-file
    config:
      platform: linux
      image_resource:
          type: docker-image
          source:
            repository: centos
            tag: latest
      inputs:
      - name: tanzu-rel-repo
      run:
        path: cat
        dir: tanzu-rel-repo/bom/
        args:
          - 'rel.yaml'
      