resources:
- name: tanzu-rel-repo
  type: git
  source:
    uri: git@github.com:nnikunj-vmw/tanzu-release.git
    private_key:  ((git_private_key))
    branch: ((branch))
  check_every: 1m
jobs:
- name: lcm
  plan: 
  - get: tanzu-rel-repo
    trigger: true
  - task: parse-bom
    vars:
      docker_user_name: ((docker_user_name))
      docker_password: ((docker_password))
    file: tanzu-rel-repo/tasks/parseBom.yaml
