platform: linux
run:
  path: tasks/scripts/parseBom.py
  dir:  tanzu-rel-repo
inputs:
- name: tanzu-rel-repo
params:
  concourse_coordinates: ((concourse_coordinates))
outputs:
  - name: bom-version
image_resource:
  type: docker-image
  source:
    username: ((docker_user_name))
    password: ((docker_password))
    repository: nilabhnikunj/concourse-cli
    tag: latest