platform: linux
run:
  path: tanzu-rel-repo/tasks/scripts/console-print.sh
  dir:  tanzu-rel-repo
inputs:
- name: bom-version
- name: tanzu-rel-repo
params:
  concourse_coordinates: ((concourse_coordinates))
image_resource:
  type: docker-image
  source:
    username: ((docker_user_name))
    password: ((docker_password))
    repository: nilabhnikunj/concourse-cli
    tag: latest