platform: linux
run:
  path: tasks/scripts/console-print.sh
  dir:  tanzu-rel-repo
inputs:
- name: tanzu-rel-repo
params:
  concourse_coordinates: ((concourse_coordinates))
image_resource:
  type: docker-image
  source:
    username: irisdev21
    password: 4d96b731-f976-4283-a956-20a58a171601
    repository: nilabhnikunj/concourse-cli
    tag: latest